/*
 * This source file was generated by the Gradle 'init' task
 */
package de.infolektuell.gradle.bass

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GradleBassPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'org.example.greeting'")
            }
        }
    }
    companion object {
        const val PLUGIN_NAME = "de.infolektuell.bass"
    }
}
